version: 0.0
os: linux
files:
   - source: .
     destination: /home/ec2-user/bisb-uat
     overwrite: true
permissions:
   - object: /home/ec2-user/bbk-uat
     pattern: "**"
     owner: ec2-user
     group: root
     type:
       - directory
   
hooks:
  ApplicationStart:
    - location: start_deployment.sh
      timeout: 6000
      runas: ec2-user
